# はじめに {.unnumbered}

## 講義の目的と概要

生態系の定量的な観測、評価、予測は、生物多様性の損失による社会リスクの低減や、自然のもつ多面的な機能を活用した社会づくりにとって不可欠です。本講義では、生態系の物理・生物環境を定量的に観測し、その地理的な成立要因や人間社会に対する影響を理解するための方法を紹介します。GISを用いた解析等のグループワークを交えながら、身近な自然を定量的に観測・評価する方法について知り、人文・自然地理的な視点から考察する力を養うことを目標とします。授業は基本的に二回一組でテーマを変えながら行い、前半ではテーマに関する講義とグループワークの導入、後半ではグループワークについての発表と議論を行います。授業時間外で成績は各回の発表への貢献（20%）と、グループワークの中から一つテーマを選び**深掘りして個々人が書く**レポート（80%）で行います。

### 講義のイメージ

-   1回目a: 講義\
    テーマの内容や扱う方法、実際の研究における活用などについての紹介

-   1回目b: 導入\
    サンプルデータを触ってみる、グループワークを始める

-   （授業時間外）\
    グループワークの進行

-   2回目a: グループワークの内容をまとめる

-   2回目b: 各グループ10分程度で発表、議論

## 使うツールと目的

-   [QGIS](https://docs.qgis.org/3.40/ja/docs/gentle_gis_introduction/index.html)\
    フリーで使えるGISソフト。地図の表示、可視化、簡単な解析や編集ができる。授業では、主に解析結果の可視化に使います。

-   [R・RStudio](https://www.tku.ac.jp/iss/guide/classroom/soft/rrstudio-desktop.html)\
    統計解析やデータの可視化に強いプログラミング言語。構文が簡単でGISも意外と得意。このオンラインテキストもRStudioで書いてるし、僕は論文全部RStudioで書いてます。授業では、衛星画像をはじめとした地理情報解析や生息適地モデルの構築に使います。

## 扱うテーマ

1.  （準備編）生態系観測の意義と地理学の接点（第一回）
2.  （準備編）生態系リモートセンシングの基礎（第一回）
3.  （準備編）QGISとRStudioのインストールと基礎（第二回）
4.  （準備編）RStudioを用いた地理情報解析の基礎（第三回、第四回）
5.  衛星画像による生態系観測（第五回、第六回）
6.  地上撮影写真による生態系観測（第七回、第八回）
7.  音響データによる生態系観測（第九回、第十回）
8.  生物の地理的分布を説明・予測するモデル（第十一回、第十二回）
9.  自然地理学と社会（第十三回、第十四回）
